name: Ueberbiber
main: com.stroebitzer.minecraft.ueberbiber.Plugin
api-version: 1.20
version: 1.0
commands:
  dragon:
  firework:
  snowballfight:
  buildinghelp:
  goldenrabbit:
  golem:
  watermlg:
